Document: hedgehog
Title: Debian hedgehog Manual
Author: <insert document author here>
Abstract: This manual describes what hedgehog is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hedgehog/hedgehog.sgml.gz

Format: postscript
Files: /usr/share/doc/hedgehog/hedgehog.ps.gz

Format: text
Files: /usr/share/doc/hedgehog/hedgehog.text.gz

Format: HTML
Index: /usr/share/doc/hedgehog/html/index.html
Files: /usr/share/doc/hedgehog/html/*.html
